# Generated by Django 4.2.7 on 2024-01-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cargo_funcao', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('ddd_telefone', models.CharField(max_length=3)),
                ('complemento', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('orgao', models.CharField(default='', max_length=50)),
                ('lotacao_de_exercicio', models.CharField(default='', max_length=50)),
                ('matricula_siape', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('matricula', models.CharField(max_length=20)),
                ('tipo_paciente', models.CharField(max_length=20)),
                ('cargo_funcao', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('ddd_telefone', models.CharField(max_length=3)),
                ('complemento', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissionaldasaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('identificacao_unica', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('ddd_telefone', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('area', models.CharField(default='', max_length=50)),
                ('unidade_siass', models.CharField(default='', max_length=50)),
                ('formacao', models.CharField(max_length=20)),
                ('conselho', models.CharField(max_length=20)),
                ('registro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chegada', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_atendimento', models.CharField(choices=[('confirmado', 'Confirmado'), ('ausente', 'Ausente'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('data_agendamento', models.DateTimeField()),
                ('prioridade_atendimento', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.paciente')),
                ('profissional_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.profissionaldasaude')),
            ],
        ),
    ]
