# Generated by Django 4.2.7 on 2023-11-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cargo_funcao', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(default='nome', max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('ddd_telefone', models.CharField(max_length=3)),
                ('complemento', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('orgao', models.CharField(default='', max_length=50)),
                ('lotacao_de_exercicio', models.CharField(default='', max_length=50)),
                ('matricula_siape', models.CharField(max_length=20)),
            ],
        ),
    ]
