# Generated by Django 4.2.7 on 2024-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_agendamento_justificativa_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_paciente',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Servidor', 'Servidor'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
