# Generated by Django 4.2.7 on 2023-11-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_administrativo'),
        ('consulta', '0002_agendamento'),
    ]

    operations = [
    ]
