# Generated by Django 4.2.7 on 2023-11-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_merge_0002_administrativo_0002_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionaldasaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('identificacao_unica', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(default='nome', max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('ddd_telefone', models.CharField(max_length=3)),
                ('complemento', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('area', models.CharField(default='', max_length=50)),
                ('unidade_siass', models.CharField(default='', max_length=50)),
                ('formacao', models.CharField(max_length=20)),
                ('conselho', models.CharField(max_length=20)),
                ('registro', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='medico',
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional_saude',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consulta.profissionaldasaude'),
            preserve_default=False,
        ),
    ]
