# Generated by Django 4.2.7 on 2024-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_alter_paciente_tipo_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cargo_funcao',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
