# Generated by Django 4.2.7 on 2024-01-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_alter_paciente_cargo_funcao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilaEspera',
        ),
    ]
