# Generated by Django 4.2.7 on 2024-01-15 11:11

from django.db import migrations, models
import django.db.models.deletion


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_delete_filaespera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('anamnese', models.TextField()),
                ('exame_fisico', models.TextField()),
                ('exames_complementares', models.TextField()),
                ('pdf_exames', models.FileField(blank=True, null=True, upload_to='exames_pdfs/')),
                ('diagnostico', models.TextField()),
                ('conduta', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.paciente')),
                ('profissional_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.profissionaldasaude')),
            ],
        ),
    ]
