# Generated by Django 4.2.7 on 2024-01-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_remove_atendimento_data_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='manha', max_length=10),
        ),
    ]
