# Generated by Django 4.2.7 on 2024-01-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_agendamento_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10),
        ),
    ]
