# Generated by Django 5.0.1 on 2024-01-26 17:13

import consulta.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_alter_agendamento_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profissionaldasaude',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='cpf',
            field=models.CharField(max_length=14, validators=[consulta.models.validate_unique_cpf]),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='email',
            field=models.EmailField(max_length=254, validators=[consulta.models.validate_unique_email]),
        ),
    ]
