# Generated by Django 5.0.1 on 2024-02-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_administrativo_usuario_profissionaldasaude_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(verbose_name='Data Agendamento'),
        ),
    ]
