# Generated by Django 5.0.1 on 2024-02-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_alter_agendamento_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionaldasaude',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profissionaldasaude',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
    ]
