# Generated by Django 5.0.1 on 2024-03-19 13:18

import consulta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0012_alter_profissionaldasaude_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_agendamento', 'paciente__nome'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['agendamento']},
        ),
        migrations.AlterModelOptions(
            name='profissionaldasaude',
            options={'ordering': ['nome'], 'verbose_name': 'Profissonal de saúde', 'verbose_name_plural': 'Profissonais de saúde'},
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='ddd_telefone',
            field=models.CharField(help_text='Com DDD.', max_length=14, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='AC', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, validators=[consulta.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='profissionaldasaude',
            name='ddd_telefone',
            field=models.CharField(help_text='Com DDD.', max_length=14, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='profissionaldasaude',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='AC', max_length=2, verbose_name='UF'),
        ),
    ]
