# Generated by Django 5.0.1 on 2024-03-19 13:24

import consulta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0013_alter_agendamento_options_alter_atendimento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='cpf',
            field=models.CharField(max_length=14, validators=[consulta.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='profissionaldasaude',
            name='cpf',
            field=models.CharField(max_length=14, validators=[consulta.models.validate_cpf]),
        ),
    ]
