# Generated by Django 5.0.1 on 2024-04-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0017_alter_paciente_bairro_alter_paciente_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='orgao',
        ),
    ]
