# Generated by Django 5.0.1 on 2024-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0019_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ddd_telefone',
            field=models.CharField(max_length=8),
        ),
    ]
