# Generated by Django 5.0.1 on 2024-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0021_arquivoexame_remove_atendimento_pdf_exames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='pdf_exames',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='pdf_exames',
            field=models.FileField(blank=True, null=True, upload_to='exames_pdfs/'),
        ),
    ]
