# Generated by Django 5.0.1 on 2024-04-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0021_arquivoexame_remove_atendimento_pdf_exames_and_more'),
        ('consulta', '0021_documento_remove_atendimento_pdf_exames_and_more'),
    ]

    operations = [
    ]
