# Generated by Django 5.0.1 on 2024-04-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0022_remove_atendimento_pdf_exames_atendimento_pdf_exames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArquivoExame',
        ),
    ]
