# Generated by Django 5.0.1 on 2024-04-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0022_merge_20240405_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
