# Generated by Django 5.0.1 on 2024-04-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0023_delete_arquivoexame'),
        ('consulta', '0023_delete_documento'),
    ]

    operations = [
    ]
