# Generated by Django 5.0.1 on 2024-06-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0024_merge_0023_delete_arquivoexame_0023_delete_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status_atendimento',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('ausente', 'Ausente'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido')], default='pendente', max_length=20),
        ),
    ]
