# Generated by Django 5.0.1 on 2024-05-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0024_merge_0023_delete_arquivoexame_0023_delete_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status_atendimento',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('ausente', 'Ausente'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='AtestadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('dias_afastamento', models.IntegerField()),
                ('cid', models.CharField(max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
