# Generated by Django 5.0.1 on 2024-06-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0025_alter_agendamento_status_atendimento_atestadomedico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atestadomedico',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Atestado Médico', 'verbose_name_plural': 'Atestados Médicos'},
        ),
        migrations.RemoveField(
            model_name='atestadomedico',
            name='data_consulta',
        ),
        migrations.RemoveField(
            model_name='atestadomedico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='atestadomedico',
            name='profissional',
        ),
        migrations.AddField(
            model_name='atestadomedico',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atestado', to='consulta.agendamento'),
        ),
    ]
