# Generated by Django 5.0.1 on 2024-06-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0025_alter_agendamento_status_atendimento'),
        ('consulta', '0027_alter_atestadomedico_agendamento'),
    ]

    operations = [
    ]
