# Generated by Django 5.0.1 on 2024-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0028_merge_20240611_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='cid',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dias_afastamento',
            field=models.IntegerField(default=0),
        ),
    ]
