# Generated by Django 5.0.1 on 2024-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0029_atendimento_cid_atendimento_dias_afastamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='cid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='dias_afastamento',
            field=models.IntegerField(),
        ),
    ]
