# Generated by Django 5.0.1 on 2024-06-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0030_alter_atendimento_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='cid',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='dias_afastamento',
            field=models.IntegerField(default=0),
        ),
    ]
