# Generated by Django 5.0.1 on 2024-06-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0031_alter_atendimento_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='dias_afastamento',
        ),
    ]
