# Generated by Django 5.0.1 on 2024-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0037_profissionaldasaude_nome_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitamedica',
            name='tipo',
            field=models.CharField(choices=[('simples', 'Simples'), ('controle_especial', 'Controle Especial')], default='simples', max_length=20),
        ),
    ]
