# Generated by Django 5.0.1 on 2024-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0038_receitamedica_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atestadomedico',
            name='texto_padrao',
            field=models.TextField(default='Atesto que o(a) paciente {paciente} esteve em consulta no dia {data_consulta}, e necessita de {dias_afastamento} dias de afastamento de suas atividades normais, para sua convalescença.'),
        ),
    ]
