# Generated by Django 5.0.1 on 2024-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0039_atestadomedico_texto_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestadomedico',
            name='texto_padrao',
            field=models.TextField(),
        ),
    ]
