# Generated by Django 5.0.1 on 2024-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0040_alter_atestadomedico_texto_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateField(verbose_name='Data Agendamento'),
        ),
        migrations.AlterField(
            model_name='atestadomedico',
            name='texto_padrao',
            field=models.TextField(default='Atesto que o(a) paciente esteve em consulta no dia {{ data_consulta }}, e necessita de [[DIAS]] dias de afastamento de suas atividades normais, para sua convalescença.'),
        ),
    ]
