# Generated by Django 5.0.1 on 2024-08-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0042_atendimento_fim_atendimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_laudo', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='consulta.agendamento')),
            ],
            options={
                'verbose_name': 'Laudo',
                'verbose_name_plural': 'Laudos',
                'ordering': ['-data_laudo'],
            },
        ),
    ]
