# Generated by Django 5.0.1 on 2024-10-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0045_atendimento_medico_responsavel_atendimento_privado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='medico_logado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_realizados', to='consulta.profissionaldasaude'),
        ),
    ]
