# Generated by Django 5.0.1 on 2024-10-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0046_atendimento_medico_logado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativo',
            options={'ordering': ['-nome'], 'verbose_name': 'Administrativo', 'verbose_name_plural': 'Administrativo'},
        ),
    ]
