# Generated by Django 5.0.1 on 2024-11-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0047_alter_administrativo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_confirmacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='inicio_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
