# Generated by Django 5.0.1 on 2024-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0048_agendamento_horario_cancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='horario_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
